version: '3.8'

services:
  db:
    container_name: 'db'
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spring-boot-docker
    ports:
      - '5432:5432'